name: Success Worlflow Run

on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: macos-12
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: echo hello
        run: echo hello

